### ISSUE TITLE
[1.11.2] Opening a parcel doesn't consume the parcel

### ISSUE THREAD

**Issue by SeriousCreeper** [A13XIS/dendrology-legacy-mod#10]
Heya,

playing the latest version of Ancient Trees L and when i right click the parcel the item doesn't get consumed, i can just keep opening it (in survival mode).

Looking at the onItemRightClick method, i think you are not decreasing the item stack after using it? 

Thanks,
SC

**Comment by A13XIS** [comment]
Yup, That's it.

Fix: https://github.com/A13XIS/dendrology-legacy-mod/blob/1.11/testing/dendrology-1.11.2-L-RC1.jar
