### ISSUE TITLE
Leaf Blocks don't decay

### ISSUE THREAD

**Issue by Scratchman** [A13XIS/dendrology-legacy-mod#11]
Ancient tree leaf blocks don't decay once the logs are removed.

Latta with all the logs removed .. https://imgur.com/a/JX8IG

Porforr .. https://imgur.com/a/FQfuo

Nothing on the console to indicate why.

**Comment by A13XIS** [comment]
Fixed for 1.11.2
I will post the new version on the project page after I fixed older versions (until 1.9) as well.

**Comment by Scratchman** [comment]
so, you'll be skipping 1.10.2?
I'm sorry i should've mentioned this was the 1.10.2 version.

**Comment by A13XIS** [comment]
Nope. Fixed all three supported versions.
You can download the newest version on the project page ([1.10.2-L1.10.2](https://minecraft.curseforge.com/projects/ancient-trees-l/files/2413113))
