### ISSUE TITLE
[1.10.2] World generator hang

### ISSUE THREAD

**Issue by WildKarrade** [A13XIS/dendrology-legacy-mod#12]
There is not crash log to go with this, but basically what happens is with some worlds it will try to load a chunk and hand the world generation indefinitely. At which point the serverwatchdog max tick time kicks in and kills the server. I didn't know if any optimization work is planned for the mod but it would be greatly appreciated so that it's usable with other worldgen mods like recurrent complex, RTG. BoP, ATG, etc.

**Comment by A13XIS** [comment]
Found an infinite loop in one of the tree generators. Fix will be deployed with the next update.
