### ISSUE TITLE
[1.10.2] Crash

### ISSUE THREAD

**Issue by ghost** [A13XIS/dendrology-legacy-mod#13]
After updating both Ancient Trees and Kore Sample to 1.10.2-L1.2, I experience the following crash:

[crash-2017-04-29_02.06.49-client.txt](https://github.com/A13XIS/dendrology-legacy-mod/files/965777/crash-2017-04-29_02.06.49-client.txt)

:-/

Forge: 1.10.2-12.18.3.2281

**Comment by ghost** [comment]
Same here, I'm on 1.11.2. [my crashlog](https://pastebin.com/Adzb6BVC).

**Comment by A13XIS** [comment]
Bug confirmed. Koresample was not obfuscated propperly.
Fixed version was uploaded to project page (awaiting approval)
EDIT: The error happened within Kore Sample so you have to download the new version of this mod (it has the same name/version as the broken one had, which I've deleted)
