### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by 0Navis0** [A13XIS/dendrology-legacy-mod#14]
I get this crash with new version https://pastebin.com/2vR6eJUH

**Comment by A13XIS** [comment]
When did you download the mod?
I uploaded a fixed version (of Kore Sample, since this is where the error was) half an hour ago.
It's even got approved already

**Comment by 0Navis0** [comment]
Oh yeah sorry Curse launcher hadn't downloaded correctly the last version of Kore Sample, problem of synchronisation. Anyway it's solved, sorry for the bothering.
