### ISSUE TITLE
[1.10.2]Crash after break few leaves blocks

### ISSUE THREAD

**Issue by Blatts12** [A13XIS/dendrology-legacy-mod#15]
https://pastebin.com/bX9TPYKH

Should I report this to LevelUp dev?

BTW
I broke all wood blocks and leaves didn't disappear

**Comment by A13XIS** [comment]
What's a LevelUp dev?
already found the problem. It'll be fixed soon.

**Comment by A13XIS** [comment]
BTW In version 1.2 of the mod leaf decay works (with every tree type). I just double checked that.
