### ISSUE TITLE
java null pointer exception when loading Minecraft

### ISSUE THREAD

**Issue by 0Navis0** [A13XIS/dendrology-legacy-mod#17]
I get this while loading Minecraft. I use Minecraft 1.11.2 and Forge 13.20.0.2309. https://pastebin.com/CzWD4fyS

**Comment by A13XIS** [comment]
I didn't fix it, but the error doesn't occur with the [NEW version](https://minecraft.curseforge.com/projects/ancient-trees-l/files/2433519) of Ancienttrees (and Koresample)
