### ISSUE TITLE
[Fixed]Crash when shift-clicking chest inventory

### ISSUE THREAD

**Issue by ghost** [A13XIS/dendrology-legacy-mod#2]
I filed an issue here: https://minecraft.curseforge.com/projects/ancient-trees-l/issues/1
But for some reason it gets marked as spam?

Anyway, I'll copy the issue here.
Version 1.10.2-L1.0.1
Tested with Forge 12.18.3.2221 / 2234 / 2239
 
During loadscreen the log-file states that this mod is spamming the log and stops logging, also I notice that during post-install, this mod causes JEI to stall for a minute.
 
In game, when opening a chest and shift-clicking items (not saplings per se) from the chest into the inventory, crashes the game. Removing this mod resolves the issue.

Crash log is on the aforementioned link.

**Comment by A13XIS** [comment]
This one is interesting. I got another person with a similar problem (Creative inventory instead of Chest)
Did you play on a certain modpack?

**Comment by ghost** [comment]
I play on a pack I made myself. I think the list of mods is part of the log? Otherwise I could send you a list. One thing I didn't mention is that the game does not crash to desktop right away; it simply switches to the dirt-screen with the message 'shutting down server' (or something to that effect) and then goes straight to desktop. Also I use MultiMC if that makes a difference?

**Comment by A13XIS** [comment]
Yes, it's in the crash report. No, MultiMC doesn't affect this in any way. The other person having this problem used the default launcher. I think...

**Comment by A13XIS** [comment]
I fixed the spamming issue. 
Please try to run this version: 
[https://github.com/A13XIS/dendrology-legacy-mod/blob/master/testing/dendrology-1.10.2-L1.rc.jar](https://github.com/A13XIS/dendrology-legacy-mod/blob/master/testing/dendrology-1.10.2-L1.rc.jar)
Does it still crash the game? If so, does the game also crash when opening the creative inventory?
**Edit**: If this version does crash, please try to remove optifine and try again.
Sorry, for giving you so many test cases, but everything works fine for me and I can't do anything from here.

**Comment by ghost** [comment]
I'm about ready to go to bed, will test tomorrow and let you know. Thnx

**Comment by ghost** [comment]
Tested in Survival and Creative; no more log-spamming, JEI no longer stalls during init, and so far no crashes. So it seems to work now. :)

**Comment by ghost** [comment]
Just to let you know; I played for 6 hours straight today with this version and no problems occurred.
