### ISSUE TITLE
[1.11.2] Crashed randomly?

### ISSUE THREAD

**Issue by SeriousCreeper** [A13XIS/dendrology-legacy-mod#3]
Heya!

Just adding your mod to my pack to give it a shot, I spawned in some planks in creative to check them out and eventually continued exploring the world, and suddenly it crashed with this: http://pastebin.com/jKY1RhdM 

Using the latest versions of your mod, the core one, forge. 

Let me know if i can provide any other info that would be helpful!

Cheers,
SC

**Comment by A13XIS** [comment]
Yup. Already know about this. Not sure why it happens though.
in 1.10.2 everything seems fine in this regard.

**Comment by A13XIS** [comment]
Got it --> [1.11.2-L1.0.1](https://minecraft.curseforge.com/projects/ancient-trees-l/files/2387393)

**Comment by SeriousCreeper** [comment]
Awesome, thank you! :D
