### ISSUE TITLE
The configurable sapling drop rate may not work

### ISSUE THREAD

**Issue by DraconianBeryl** [A13XIS/dendrology-legacy-mod#4]
I started an attempt to update this mod and had to abandon it due to a lack of time.  I'm glad to see that someone else is picking this mod up.

While I was doing my work I noticed that one of the tree types, the one that generates with the fewest leaf blocks (sorry I can't remember the name) dropped (on average) very slightly less than 1 sapling per tree and had a relatively high chance that any specific tree might not drop any saplings.  This led me to try tuning the default drop rate values, which led me to notice that, in my testing, it didn't look like the configurable drop rate was working.

I created commit https://github.com/DraconianBeryl/Dendrology/commit/d119114abb6fbd40b80391fdb65050cd5c06f9af which appears to show that the code that uses the configurable drop rate is never called (the log messages don't show up).

I did not come up with a solution to this, as it exposed more ignorance of the Minecraft internals flow than I had the time to correct.

**Comment by A13XIS** [comment]
Alright, I'll check it.

**Comment by A13XIS** [comment]
Well, it didn't, since this property wasn't checked anywhere in the code.
It'll be fixed with the upcoming release.
