### ISSUE TITLE
JVM restart required to get multiple of the same sapling out of the ancient parcels

### ISSUE THREAD

**Issue by DraconianBeryl** [A13XIS/dendrology-legacy-mod#5]
If you spend time in creative spam-right-clicking the ancient parcels you will eventually start getting reports of being given more than one of a type of sapling, but no second sapling is given to the player.  If this is done in a multiplayer environment, only one player can receive a sapling of this type.

Every JVM restart (server restart for multi-player, or whole client restart for single-player), a second sapling of that type can be obtained from a parcel.

This is because the parcel code drops a reference to an itemstack contained by a singleton object, which is then depleted when the player picks up the drop.

My solution was to drop copy of the itemstack.  Very simple and probably flawed in some way that I'm completely ignorant of.  You can see it in https://github.com/MinecraftModArchive/Dendrology/commit/58c7a494736b2d3a940f7e0898f76fbd50fd71b8.

I don't recommend trying to merge my commit, as I started my work by merging the KoreSample mod into the Dendrology mod, which was probably the first in a string of bad ideas.  :)

**Comment by A13XIS** [comment]
Thank you for your help, but I fixed this already (at least for 1.9.4-1.11.2)
For some reason the number of items in a stack is reduced by 1 after every you got an item. Something making sense for the 1.7 system (maybe), but not anymore.
